services: # 실제 실행할 컨테이너들
  postgres: # 컨테이너1 postgres 컨테이너
    image: postgres:17
    container_name: discodeit-postgres
    environment: # DB에 필요한 환경 변수 설정(.env 파일 활용)
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: # 필요한 포트 매핑
      - "${POSTGRES_HOST_PORT}:5432"
    volumes: # 컨테이너가 삭제되거나 재시작되어도 유지할 저장 공간
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro  # schema.sql 자동 실행
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  app: # 컨테이너2 app 컨테이너(Spring Boot 애플리케이션 실행)
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discodeit-app
    depends_on:
      postgres: # 서비스 간 의존성 설정
        condition: service_healthy
    environment: # 환경 변수 설정(.env 파일 활용)
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      DISCODEIT_STORAGE_TYPE: local
      DISCODEIT_STORAGE_LOCAL_ROOT_PATH: /app/.discodeit/storage
      SERVER_PORT: 80
      JVM_OPTS: ${JVM_OPTS}
    ports: # 필요한 포트 매핑
      - "${APP_HOST_PORT}:80"
    volumes:
      - app_storage:/app/.discodeit/storage

volumes:
  postgres_data:
  app_storage: